// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event_registry.proto

package event_listener

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message .
type Handler struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=Port,proto3" json:"Port,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	MessageId            string   `protobuf:"bytes,3,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	LastMessageNumber    uint64   `protobuf:"varint,4,opt,name=LastMessageNumber,proto3" json:"LastMessageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_00dfe5a5482fc9a0, []int{0}
}

func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (m *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(m, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

func (m *Handler) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Handler) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Handler) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Handler) GetLastMessageNumber() uint64 {
	if m != nil {
		return m.LastMessageNumber
	}
	return 0
}

// The response message
type RegisterResponse struct {
	// 0 OK
	Response             int32    `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00dfe5a5482fc9a0, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetResponse() int32 {
	if m != nil {
		return m.Response
	}
	return 0
}

func init() {
	proto.RegisterType((*Handler)(nil), "event_listener.Handler")
	proto.RegisterType((*RegisterResponse)(nil), "event_listener.RegisterResponse")
}

func init() { proto.RegisterFile("event_registry.proto", fileDescriptor_00dfe5a5482fc9a0) }

var fileDescriptor_00dfe5a5482fc9a0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4d, 0x4a, 0x03, 0x41,
	0x10, 0x85, 0x6d, 0x1d, 0x7f, 0x52, 0xa0, 0x68, 0x11, 0x71, 0x08, 0x2e, 0x86, 0x59, 0xcd, 0x42,
	0x66, 0xa1, 0x47, 0x10, 0xd1, 0x40, 0x14, 0xe9, 0xb8, 0x97, 0x0e, 0x53, 0x84, 0x81, 0xb1, 0x3b,
	0x54, 0x55, 0x04, 0x0f, 0xe0, 0xc1, 0xbc, 0x99, 0xa4, 0xd3, 0x89, 0x1a, 0x97, 0xd9, 0x55, 0xbd,
	0x47, 0xbf, 0x7e, 0x1f, 0x05, 0x7d, 0x7a, 0x27, 0xaf, 0xaf, 0x4c, 0xd3, 0x56, 0x94, 0x3f, 0xea,
	0x19, 0x07, 0x0d, 0x78, 0xb2, 0x54, 0xbb, 0x56, 0x94, 0x3c, 0x71, 0xf9, 0x69, 0xe0, 0xf0, 0xc1,
	0xf9, 0xa6, 0x23, 0x46, 0x84, 0xec, 0x39, 0xb0, 0xe6, 0xa6, 0x30, 0xd5, 0xb1, 0x8d, 0x33, 0x0e,
	0xe0, 0xe8, 0xb6, 0x6b, 0xc9, 0xeb, 0xb0, 0xc9, 0x77, 0x0b, 0x53, 0xf5, 0xec, 0x7a, 0xc7, 0x4b,
	0xe8, 0x3d, 0x92, 0x88, 0x9b, 0xd2, 0xb0, 0xc9, 0xf7, 0xa2, 0xf9, 0x23, 0xe0, 0x15, 0x9c, 0x8d,
	0x9c, 0x68, 0x12, 0x9e, 0xe6, 0x6f, 0x13, 0xe2, 0x3c, 0x2b, 0x4c, 0x95, 0xd9, 0xff, 0x46, 0x59,
	0xc3, 0xa9, 0x8d, 0x4d, 0x89, 0x2d, 0xc9, 0x2c, 0x78, 0xa1, 0xc5, 0xdf, 0x9c, 0xe6, 0xd8, 0x69,
	0xdf, 0xae, 0xf7, 0xeb, 0x2f, 0x03, 0xfd, 0xe5, 0x03, 0x76, 0xda, 0x06, 0x3f, 0x4a, 0x40, 0x38,
	0x5e, 0xe9, 0xc4, 0x77, 0x0b, 0xd4, 0x15, 0xdc, 0x45, 0xfd, 0x97, 0xbc, 0x4e, 0xc6, 0xa0, 0xd8,
	0x34, 0x36, 0x7b, 0x94, 0x3b, 0xf8, 0x02, 0xe7, 0xf7, 0xa4, 0xbf, 0xf3, 0xc6, 0xea, 0x74, 0x2e,
	0x5b, 0xa5, 0x4e, 0x0e, 0xe2, 0x49, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x18, 0xe4,
	0xb6, 0xaa, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistrationListenerClient is the client API for RegistrationListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistrationListenerClient interface {
	// Sends a command
	RegisterEventHandler(ctx context.Context, in *Handler, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetEventHandlerStatus(ctx context.Context, in *Handler, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registrationListenerClient struct {
	cc *grpc.ClientConn
}

func NewRegistrationListenerClient(cc *grpc.ClientConn) RegistrationListenerClient {
	return &registrationListenerClient{cc}
}

func (c *registrationListenerClient) RegisterEventHandler(ctx context.Context, in *Handler, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/event_listener.RegistrationListener/RegisterEventHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationListenerClient) GetEventHandlerStatus(ctx context.Context, in *Handler, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/event_listener.RegistrationListener/GetEventHandlerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationListenerServer is the server API for RegistrationListener service.
type RegistrationListenerServer interface {
	// Sends a command
	RegisterEventHandler(context.Context, *Handler) (*RegisterResponse, error)
	GetEventHandlerStatus(context.Context, *Handler) (*RegisterResponse, error)
}

func RegisterRegistrationListenerServer(s *grpc.Server, srv RegistrationListenerServer) {
	s.RegisterService(&_RegistrationListener_serviceDesc, srv)
}

func _RegistrationListener_RegisterEventHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handler)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationListenerServer).RegisterEventHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_listener.RegistrationListener/RegisterEventHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationListenerServer).RegisterEventHandler(ctx, req.(*Handler))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationListener_GetEventHandlerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handler)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationListenerServer).GetEventHandlerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_listener.RegistrationListener/GetEventHandlerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationListenerServer).GetEventHandlerStatus(ctx, req.(*Handler))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistrationListener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event_listener.RegistrationListener",
	HandlerType: (*RegistrationListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEventHandler",
			Handler:    _RegistrationListener_RegisterEventHandler_Handler,
		},
		{
			MethodName: "GetEventHandlerStatus",
			Handler:    _RegistrationListener_GetEventHandlerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event_registry.proto",
}
